version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  library:
    image: rsoi_lab2_library
    container_name: library
    restart: on-failure
    ports:
      - "8060:8060"

  rating:
    image: rsoi_lab2_rating
    container_name: rating
    restart: on-failure
    ports:
      - "8050:8050"

  reservation:
    image: rsoi_lab2_reservation
    container_name: reservation
    restart: on-failure
    ports:
      - "8070:8070"

  api_gateway:
    image: rsoi_lab2_api
    container_name: api_gateway
    restart: on-failure
    ports:
      - "8080:8080"

volumes:
  db-data:
  cache:
    driver: local