name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      - name: Build docker containers
                  cd postgres
                  chmod +x 20-create-databases.sh
                  ./20-create-databases.sh
                  cd ../src
        run: |
          cd src
          chmod +x build_docker.sh
          ./build_docker.sh

      - name: Build images
        timeout-minutes: 10
        run: docker compose build

      - name: Run containers
        timeout-minutes: 5
        run: |
          docker compose up -d
          ./scripts/wait-script.sh
        env:
          WAIT_PORTS: 8080,8070,8060,8050
        # ./scripts/wait-script.sh
        #  sleep 10

      - name: Fill database
        run: |
          cd src
          chmod +x fill_db.sh
          ./fill_db.sh
          date +%Y:%m:%d_%H:%M:%S
          sleep 20
          date +%Y:%m:%d_%H:%M:%S

      - name: Run API Tests
        timeout-minutes: 5
        run: |
          date +%Y:%m:%d_%H:%M:%S
          ./scripts/test-script.sh
        env:
          VARIANT: v4
          SERVICE_NAME: rating
          PORT_NUMBER: 8050

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 3
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"

      - name: Stop containers
        if: always()
        continue-on-error: true
        run: docker compose down -v